### ISSUE TITLE
[NSML] Baseline 코드 실행 에러

### ISSUE THREAD

**Issue by thisisiron** [hunminjeongeum-korean-competition-2021/speaker-recognition#11]
# 주제
-  NSML baseline 에러 발생

# 상황 (자세히 작성해주시면 좋습니다.)
- NSML baseline 코드 실행 (nsml run -d speaker -e main.py) 에러 발생

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
![image](https://user-images.githubusercontent.com/23303033/136765322-2e731256-205e-4d16-8460-56bb13cf914e.png)

# 기타 문의 사항
-

**Comment by jihoon99** [comment]
저도 비슷한 현상이 발생합니다.
![스크린샷 2021-10-11 오후 6 36 38](https://user-images.githubusercontent.com/45288481/136768289-0f3d6b9c-0960-4da1-9b04-d2daa6ac4570.png)

**Comment by thisisiron** [comment]
#29 

문제가 해결되어서 이슈 닫습니다.
