### ISSUE TITLE
[NSML] nsml run 오류  (Session 실행이 안됩니다.)

### ISSUE THREAD

**Issue by papari1123** [hunminjeongeum-korean-competition-2021/speaker-recognition#14]
# 주제
-   nsml run ail
- 
# 상황 (자세히 작성해주시면 좋습니다.)
-  nsml run 명령어로 secession을 실행하는데, 
   launching is failed. Please contact dev team 라고 뜹니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
![image](https://user-images.githubusercontent.com/33012030/136815889-7ffd2c70-6eed-465c-88d8-b672f5cfbc9b.png)

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@papari1123 님, 
https://www.docker.com/increase-rate-limit
이슈로 확인되었는데요. 다시 한번 시도 부탁드립니다.
