### ISSUE TITLE
[NSML] Internal server error 확인 부탁드립니다

### ISSUE THREAD

**Issue by msh9184** [hunminjeongeum-korean-competition-2021/speaker-recognition#15]
# 주제
- Internal server error

# 상황 (자세히 작성해주시면 좋습니다.)
- Internal server error 체크 한번 부탁드리겠습니다. nsml login -> nsml whoami -> nsml run -e main.py -d speaker 실행 화면을 아래 첨부 드렸습니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 
![image](https://user-images.githubusercontent.com/33674982/136831643-7168eaff-274e-4127-9da4-2867af6d8e18.png)

# 기타 문의 사항
-

**Comment by ralasun** [comment]
많은 분들이 같은 문제를 계속 겪고 있는것 같은데 빠른 해결이 필요할 것 같습니다.
