### ISSUE TITLE
[NSML] session생성시 internal server error가 발생합니다.

### ISSUE THREAD

**Issue by jihoon99** [hunminjeongeum-korean-competition-2021/speaker-recognition#18]
# 주제
- 
session생성시 internal server error가 발생합니다.

# 상황 (자세히 작성해주시면 좋습니다.)
- 
baseline클론해서 run을 했을때 세션을 만드는데 실패한다고 합니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
-
login, whoami 정보는 아래와 같습니다.
![스크린샷 2021-10-12 오후 12 48 07](https://user-images.githubusercontent.com/45288481/136891367-6ad78040-f82c-47b0-974e-fa402a68df85.png)

run을 했을때 상황은 아래와 같습니다.
<img width="558" alt="스크린샷 2021-10-12 오후 12 50 01" src="https://user-images.githubusercontent.com/45288481/136891441-9d2acb6e-76c2-4e00-854e-3440b889d423.png">

사용을 하지 않았는데 리소스 상황은 아래와 같습니다.
<img width="1408" alt="image" src="https://user-images.githubusercontent.com/45288481/136891530-325df3b8-fcf9-47a1-b2ce-10f3cad11e86.png">

세션은 없는 상태입니다.
<img width="559" alt="image" src="https://user-images.githubusercontent.com/45288481/136891583-79174395-0311-4065-9d7d-076a7b9fe765.png">

# 기타 문의 사항
-
감사합니다.

**Comment by bluebrush** [comment]
@msh9184 님, nsml run에서 자원 부족일 때, 
`nsml ps` 결과 확인되시면 붙여주시면 도움이 될 것 같습니다.

**Comment by ralasun** [comment]
@msh9184 @bluebrush 저는 토요일 저녁까지 정상동작하다가 토요일 이후론 계속해서(거의 30분에 한번씩 시도중..) Internal server error가 나고 해결이 안되고 있습니다. ㅠㅠ

**Comment by msh9184** [comment]
![image](https://user-images.githubusercontent.com/33674982/136899508-0778b9b1-727c-47bb-b3df-4bc9bff58c15.png)

현 시점 실행 캡처입니다.

**Comment by ralasun** [comment]
@bluebrush nsml run -d speaker -e main.py 입니다. 토요일 저녁까지 정상으로 작동한 코드 동일하게 사용한건데 오류가 나고 있습니다. 또한 submit 도 안되고 있는데 submit 명령어는 nsml submit nia3020/speaker/49 8 입니다.

**Comment by leejiyoon7** [comment]
@bluebrush 
저도 4일간 아무것도 못하고있습니다. #11

**Comment by bluebrush** [comment]
@FYLSunghwan 님, 조치되었습니다.  이슈에 대한 원인 및 공지가 #21 에 있습니다.
