### ISSUE TITLE
[NSML] 개인 개발 프레임워크 사용 관련

### ISSUE THREAD

**Issue by msh9184** [hunminjeongeum-korean-competition-2021/speaker-recognition#2]
# 주제
- 개인 개발 프레임워크 사용 관련

# 상황 (자세히 작성해주시면 좋습니다.)
- 제공해주신 개발 환경 및 baseline 모델 이외의 개발 환경을 활용하고 싶습니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 올려주신 baseline 모델과 다른 라이브러리(tensorflow->pytorch)를 사용하여 개발이 가능한지 궁금합니다. (제공해 주신 프레임워크와 baseline 활용으로만 제한이 될 경우, 성능 개선을 위한 개발 시간보다 툴킷 숙지 및 환경 구축에 더 많은 시간이 소요 될 것 같아 문의 드립니다.)

# 기타 문의 사항
-

**Comment by dacon-murdoch** [comment]
안녕하세요.
다른 라이브러리를 사용하여 대회에 참가 가능합니다.
baseline은 참고용 코드입니다.
감사합니다.

**Comment by msh9184** [comment]
네 감사합니다!
