### ISSUE TITLE
[NSML] 로그인 에러: Initializing user information

### ISSUE THREAD

**Issue by jnh03288** [hunminjeongeum-korean-competition-2021/speaker-recognition#22]
# 주제
- 로그인 에러: Initializing user information 

# 상황 (자세히 작성해주시면 좋습니다.)
- nitializing user information Error
CLI에서 nsml 후에 baseline 코드실행 시 아래 사진과 같은 에러가 발생합니다.
Error: An error occurred while initializing user information. Please contact dev team

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 
![image](https://user-images.githubusercontent.com/59000197/136945076-77d9fe1f-d182-4b7f-ae44-1a19c013d55a.png)

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@jnh03288 님, 조치 되었습니다.
