### ISSUE TITLE
[NSML] 제출 포맷 관련 문의

### ISSUE THREAD

**Issue by jieun121070** [hunminjeongeum-korean-competition-2021/speaker-recognition#24]
# 주제
- 제출 포맷 관련 문의

# 상황 (자세히 작성해주시면 좋습니다.)
- 

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
안녕하세요. 제출 포맷 관련 문의 드립니다.

`README.md`의 화자인식 Dataset 설명 부분에는
test_data dataframe에 label 컬럼을 추가하여 대입해야 한다고 되어 있는데요.

baseline > `main.py` 코드 내의 bind_model > infer 함수에는
결과값을 `list(zip(prob, pred))` 형태로 제출해야 한다고 되어 있습니다.
둘 중 어느 방법으로 제출하면 될 지 알려주시면 감사하겠습니다.

# 기타 문의 사항
-

**Comment by msh9184** [comment]
@jieun121070 pred(score) 값과 시스템에 저장 되어 있을  label 값으로 eer이 측정 되는게 아닐까요??

**Comment by ralasun** [comment]
@taerangi @msh9184 네, 그래서 그 부분에 대한 체크가 필요합니다. baseline 코드를 보면, 아래그림과 같습니다. 

![image](https://user-images.githubusercontent.com/37501153/137082917-e5bfeeb0-9d11-43eb-8bb2-1e3388495988.png)

즉, pred 부분은 예측한 라벨이고 , prob 부분이 확률인데, 위에 답변(https://github.com/hunminjeongeum-korean-competition-2021/speaker-recognition/issues/24#issuecomment-941861617)을 보면, prob 값은 상관이 없다라고 하셔서 주최측에서 확인해주셔야 할 것 같습니다.

**Comment by taerangi** [comment]
앞서 말씀 드린 내용은 `list(zip(prob,pred))`의 포맷에서 `prob` 값이 score에 영향을 미치지 않는다는 뜻입니다.
위의 포맷에서 `pred` 값만 가져와서 채점하도록 되어있습니다.
`pred` 값에 1에 대한 확률 값, 혹은 정답으로 예측한 binary를 넣어주시면 됩니다.

참고로, baseline 코드에서는 편의상 binary 형태로 pred 값을 넣었습니다.
(threshold에 따라 binary로 답을 기재했을 때와 1에 대한 확률로 답을 기재했을 때 score가 다를 수 있습니다.)
