### ISSUE TITLE
[NSML] submit 메모리 관련

### ISSUE THREAD

**Issue by leejiyoon7** [hunminjeongeum-korean-competition-2021/speaker-recognition#33]
# 주제
- submit 메모리 관련

# 상황 (자세히 작성해주시면 좋습니다.)
- submit시 메모리가 너무 작아서 자꾸 잘 안되는데 따로 메모리양을 지정해주질 못합니다. 기본으로 24기가만 사용하게 되어있는 것 같은데 혹시 기본 메모리를 좀 늘려주실 수 없나요?

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 

# 기타 문의 사항
-

**Comment by bluebrush** [comment]
@leejiyoon7 #36 공지와 같이 
```
RAM : 60GB로 변경하였습니다. 
CPU : 7 core
```

**Comment by leejiyoon7** [comment]
@bluebrush 감사합니다.
