### ISSUE TITLE
[NSML]staus의 running을 멈추는 방법

### ISSUE THREAD

**Issue by Subin-Kim46** [hunminjeongeum-korean-competition-2021/speaker-recognition#41]
# 주제
- staus의 running을 멈추는 방법

# 상황 (자세히 작성해주시면 좋습니다.)
-  서브밋으로 제출을 했는데 cmd 창을 종료해도 러닝이 멈추지 않습니다. 혹시 실험을 멈추는 nsml 코드나 기타 방법이 있다면 알려주시면 감사하겠습니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
![err](https://user-images.githubusercontent.com/76643618/138157488-532abb1c-e2f3-4264-998b-00b0e014ea21.jpg)

# 기타 문의 사항
-

**Comment by taerangi** [comment]
nsml rm nia3016speaker/464 -f 로 시도해보시겠어요??

**Comment by Subin-Kim46** [comment]
> nsml rm nia3016/speaker/464 -f 로 시도해보시겠어요??

이 커멘드는 사용할 수 없다라고 메세지가 뜹니다

**Comment by bluebrush** [comment]
@Subin-Kim46 님, 해당 세션 종료된 것 같은데 이슈가 지속되는 것일까요?

**Comment by Subin-Kim46** [comment]
> @Subin-Kim46 님, 해당 세션 종료된 것 같은데 이슈가 지속되는 것일까요?

문제가 해결된것 같습니다. 감사합니다
