### ISSUE TITLE
[NSML] baseline 코드 실행시 오류

### ISSUE THREAD

**Issue by leejiyoon7** [hunminjeongeum-korean-competition-2021/speaker-recognition#9]
# 주제
- baseline 코드 실행시 오류

# 상황 (자세히 작성해주시면 좋습니다.)
- baseline을 기본 실행시 42번째 줄인 zero_padding = tf.zeros([max] - tf.shape(waveform), dtype = tf.float32) 에서 오류가 발생합니다.

# 내용 (첨부 가능한 이미지 추가해주시면 더 좋습니다.)
- 
![화면 캡처 2021-10-11 020746](https://user-images.githubusercontent.com/57735984/136706130-14443126-567f-4bd8-98bc-a79469778a20.png)

# 기타 문의 사항
-

**Comment by dacon-murdoch** [comment]
안녕하세요.
현재 코드 확인 중에 있습니다.
데이터 정보는 docs로 올려두었으니 참고하여 모델을 개발해 주시면 감사하겠습니다.
감사합니다.)

**Comment by taerangi** [comment]
@leejiyoon7  안녕하세요.
현재 해당 베이스라인이 메모리를 많이 소요하는 형태로 작성되어 있습니다.
(학습데이터를 줄이고 실행하면 에러가 발생하지 않을 것입니다.)
이번주중으로 보완된 베이스라인을 업로드 할 예정입니다.
감사합니다.

**Comment by leejiyoon7** [comment]
@taerangi 감사합니다
